version: '3'
services:
  admin:
    build: ./Admin
    ports:
      - "18081:18081"
    depends_on:
      - mysql

  app:
    build: ./App
    ports:
      - "18080:18080"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game_account_shop
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: