server:
  port: 18080
  servlet:
    context-path: /api

spring:
  application:
    name: Game-Account-Shop-App

  datasource:
    url: jdbc:mysql://localhost:3306/game_account_shop?useUnicode=true&characterEncoding=utf-8&isSSL=false
    username: root
    password: root