### 1. 上传图片
POST {{host}}/admin/oss/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="tt.JPG"
Content-Type: image/jpeg

< ./tt.JPG
--WebAppBoundary--
