server:
  port: 18081
  servlet:
    context-path: /admin

spring:
  application:
    name: Game-Account-Shop-Admin

  datasource:
    url: jdbc:mysql://mysql:3306/game_account_shop?useUnicode=true&characterEncoding=utf-8&isSSL=false
    username: root
    password: root

qinghaotech:
  aliyun-oss:
    region: cn-chengdu
    endpoint: oss-cn-chengdu.aliyuncs.com
    bucket: game-account-shop
    custom-endpoint: https://oss.qinghaotech.com